openimis/rest_api_c-sharp

OpenImis.DB.SqlServer/DataHelper/DataHelper.cs, OpenImis.DB.SqlServer/DataHelper/ProcedureOutPut.cs, OpenImis.RestApi/Startup.cs
`DataHelper` has been added which is used to connect to the database in the case of procedures.
In the `Startup` file, I added a record that disables the automatic `HTTP 400` support.
TASK:
https://openimis.atlassian.net/browse/OS-26
=> OS-26: DataHelper added and automatic support for HTTP 400 responses disabled

ImisRestApi/ImisRestApi/Controllers/PaymentBaseController.cs, ImisRestApi/ImisRestApi/Data/ImisBasePayment.cs, ImisRestApi/ImisRestApi/Logic/PaymentLogic.cs, ImisRestApi/ImisRestApi/Logic/ValidationBase.cs, ImisRestApi/ImisRestApi/Models/Payment/ReconciliationItem.cs, ImisRestApi/ImisRestApi/Models/Payment/ReconciliationRequest.cs, ImisRestApi/ImisRestApi/Responses/ReconciliationMessage.cs
I added new endpoint according to the documentation RFC 71v2.6.9.
The structure of the input and output data has been preserved as in the documentation.
JSON for testing in POSTMAN (http://localhost:63401/api/ProvideReconciliationData) :
- Success 200
```
{
"date_from" : "10112000",
"date_to" : "10112020"
}
```
- Missing specification of the period
```
{
"date_from" : "",
"date_to" : ""
}
```
- Beginning date follows closing date of the period
```
{
"date_from" : "10112022",
"date_to" : "10112020"
}
```
- The period is in the future
```
{
"date_from" : "10112022",
"date_to" : "10112023"
}
```
=> OTC-29: A new endpoint for api has been added

ImisRestApi/ImisRestApi/ImisRestApi.csproj, ImisRestApi/ImisRestApi/Properties/PublishProfiles/FolderProfile.pubxml
Strings from Escape/SMS are disappearing during publish. Changing the confuguration makes them persistent.
=> Added Escape/Sms strings to published api

ImisRestApi/Data/ImisBasePayment.cs, ImisRestApi/Escape/Payment/Controllers/PaymentController.cs, ImisRestApi/Escape/Payment/Data/GepgUtility.cs, ImisRestApi/Escape/Payment/Data/ImisPayment.cs
TICKET: https://openimis.atlassian.net/browse/OTC-260
In that PR I want to fix issue that @delcroip reported in that ticket on Friday with SPCode taken from configuration. I fixed this according to clues given by Patrick. 
1. Take all products from tbl Product with "SP[0-9{3}]" regex.
2. Iterate through all products in "Reconciliation" endpoint with such above condition 
3. RequestReconciliationReport - add new argument ProductSPCode.
4. SendReconcHttpRequest - add new argument ProductSPCode. 
5. Replace configuration["PaymentGateWay:GePG:SpCode"] into "ProductSPCode" in both "SendReconcHttpRequest " and "RequestReconciliationReport "
=> OTC-260: fix Reconcilation call still using config SPCODE

ImisRestApi/Escape/Payment/Data/GepgUtility.cs, ImisRestApi/appsettings.json
TICKET: https://openimis.atlassian.net/browse/OTC-259
Debugger shows sth like this after and before my changes related to that ticket. 
Before changes:
After changes:
=> OTC-259: Use app config instead of hardcoded path for the cert

ImisRestApi/Data/ImisBasePayment.cs, ImisRestApi/Escape/Payment/Data/GepgUtility.cs, ImisRestApi/appsettings.json
related to TICKET: https://openimis.atlassian.net/browse/OTC-263
Changes:
1. change certPass hardcoded - current one caused issues because that one was realized to be wrong during testing.
2. include also some changes from ticket https://openimis.atlassian.net/browse/OTC-259 - move hardcoded path to appsettings.json - the only difference is using in that PR "Path.Combine". 
3. Removed generating control number Randomly in ImisBasePayment.cs "PostReqControlNumber".
=> OTC-263: fix timeout issue on GetControlNumber

ImisRestApi/Controllers/ClaimsController.cs, ImisRestApi/Data/DataHelper.cs, ImisRestApi/Data/ImisClaims.cs, ImisRestApi/Models/ClaimOutPut.cs, ImisRestApi/Properties/launchSettings.json
Changes:
- Changed the inline sql used to retrieve claims to a SP
- Changed the format of retrieved data from one big Table with a lot of redundancy to 3 tables containing claims, items and services.
- Added a data helper to retrieve `DataSet` (instead of `DataTable`)
- Fixed the problem with missing and cloned items and services
- Changed alghoritm used to match claims with items and services to take advantage of `O(1)` search in `Dictionary`
- Changed the key used to match claims with items and services from claim code, which is not unique, to claim UUID
Additional changed:
- changed listening adress from `localhost` to `127.0.0.1` for IIS Express, which is more universal when trying to connenct Claims app in a local environment. …
=> OTC-250: Missing data in API (requested amount) during download

OpenImis.ModulesV2/InsureeModule/Repositories/FamilyRepository.cs
Changes:
- Eliminated cross join in FamilyRepository in GetByCHFID method, which was making the endpoint unusable on a larger database (like on CHFIMIS backup the request time outs after 2 minutes of waiting). This change makes the request 2-3 seconds long.
[https://openimis.atlassian.net/browse/OTC-301](https://openimis.atlassian.net/browse/OTC-301)
=> OTC-301: Fix Timeout on api/family/{CHFID} endpoint

OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/Insuree.cs
Changes:
- Changed the type of the Vulnerability field in Enrolment model to string to fix the problem with casting the 0-1 value
[https://openimis.atlassian.net/browse/OTC-334](https://openimis.atlassian.net/browse/OTC-334)
=> OTC-334: Add “Vulnerability” field in Policies app

OpenImis.ModulesV3/ClaimModule/Logic/ClaimLogic.cs, OpenImis.ModulesV3/ClaimModule/Repositories/ClaimRepository.cs, OpenImis.ModulesV3/Helpers/Extensions/StringExtensions.cs, OpenImis.RestApi/Controllers/V3/ClaimController.cs
This PR contains changes from: https://github.com/openimis/rest_api_c-sharp/pull/84
Changes:
- Claim XML which failed validation is now removed from the server
- The API now correctly differentiate between rejected and invalid claims and put only rejected claims in rejected directory
[https://openimis.atlassian.net/browse/OTC-348](https://openimis.atlassian.net/browse/OTC-348)
=> OTC-348: Add rejection state to claim submission

OpenImis.RestApi/Controllers/V3/ClaimController.cs
Changes:
- Allowed unauthorised connection for endpoints used in Claims app initialization
[https://openimis.atlassian.net/browse/OTC-356](https://openimis.atlassian.net/browse/OTC-356)
=> OTC-356: ClaimController V3 does not allow unauthorised connections

OpenImis.ePayment/Escape/Payment/Data/ImisPayment.cs
Changes:
- Added `O.ValidityTo` checks to the query assigning and printing control numbers during bulk CN request
[https://openimis.atlassian.net/browse/OTC-407](https://openimis.atlassian.net/browse/OTC-407)
=> OTC-407: ValidityTo check added in GetControlNumbersForEO

OpenImis.ModulesV3/Utils/DateTimeSerializers.cs
Changes:
-  Fixed XML serializer to use `yyyy-MM-dd` format as input for stored procedures
[https://openimis.atlassian.net/browse/OTC-431](https://openimis.atlassian.net/browse/OTC-431)
=> OTC-431: Update XML serializing format to yyyy-MM-dd

OpenImis.ModulesV3/ClaimModule/Models/DsiInputModel.cs, OpenImis.ModulesV3/ClaimModule/Models/PaymentListsInputModel.cs, OpenImis.ModulesV3/ClaimModule/Repositories/ClaimRepository.cs
Changes:
- Fixed `DsiInputModel` and `PaymentListsInputModel` to allow null in `last_update_date` field
- Fixed ClaimRepository to correctly handle null value in `last_update_date` field (GetDsi and GetPaymentLists methods)
- Removed unnecessary datetime conversion
[https://openimis.atlassian.net/browse/OTC-433](https://openimis.atlassian.net/browse/OTC-433)
=> OTC-433: Fix DSI rest API endpoints to allow null as last_update_date

OpenImis.ModulesV3/InsureeModule/Repositories/FamilyRepository.cs, OpenImis.ModulesV3/PolicyModule/Repositories/PolicyRenewalRepository.cs, OpenImis.ModulesV3/Utils/DateTimeSerializers.cs
Changes:
- Adjusted `Datetime` format used to save enrolment and policy renewal XML files. Current format does not contain colons and allow files to be saved successfully.
[https://openimis.atlassian.net/browse/OTC-434](https://openimis.atlassian.net/browse/OTC-434)
=> OTC-434: Fix policy renewal from renewal prompt

OpenImis.ModulesV3/InsureeModule/Repositories/FamilyRepository.cs
Changes:
- Removed redundant `tblFamilySMS` join effectively changing `inner join tblFamilySMS` to `left join tblFamilySMS`
=> Removed redundant FamilySMS join from FamilyRepisitory.GetByCHFID

OpenImis.ePayment/Escape/Payment/Data/ImisPayment.cs
Changed the ControlNumberToBeRequested query and included only with the payment status 1,2 and 3
https://openimis.atlassian.net/browse/OTC-495
=> OTC-495: Fetch CN for EOs, numbers to be requested needs to exclude statuses except 1,2 and 3

OpenImis.DB.SqlServer/TblProduct.cs
https://openimis.atlassian.net/browse/OTC-565
Changes:
- Changed type of MemberCount from int to short in RestApi to reflect structure of the DB.
=> OTC-565: MemberCount type changed from int to short

OpenImis.DB.SqlServer/TblProduct.cs
https://openimis.atlassian.net/browse/OTC-565
Hotfix - previous change reversed, as it was merged by accident.
Changes:
-MemberCount type changed back to int from short.
=> OTC-565: Hotfix - change reversed - type changed from short to int.

OpenImis.ModulesV3/PolicyModule/Repositories/PolicyRenewalRepository.cs
Delete the file if it already exists in the rejected folder before moving
https://openimis.atlassian.net/browse/OTC-598
=> OTC-598: Error: System.IO.IOException: Cannot create a file when that file already exists

OpenImis.ModulesV2/InsureeModule/Repositories/InsureeRepository.cs, OpenImis.ModulesV3/InsureeModule/InsureeModule.cs, OpenImis.ModulesV3/InsureeModule/Logic/FamilyLogic.cs, OpenImis.ModulesV3/InsureeModule/Logic/InsureeLogic.cs, OpenImis.ModulesV3/InsureeModule/Models/InsureeModel.cs, OpenImis.ModulesV3/InsureeModule/Repositories/InsureeRepository.cs, OpenImis.ModulesV3/OpenImis.ModulesV3.csproj, OpenImis.ModulesV3/Utils/PhotoUtils.cs
Part of [OTC-612](https://openimis.atlassian.net/browse/OTC-612). 
Photo paths are built using System.Path for compatibility with dockerized application running in linux.
=> OTC-612: Changed way photo paths are built

OpenImis.DB.SqlServer/DataHelper/DataHelper.cs, OpenImis.DB.SqlServer/ImisDB.cs, OpenImis.ModulesV3/ClaimModule/Repositories/ClaimRepository.cs, OpenImis.ModulesV3/FeedbackModule/Repositories/FeedbackRepository.cs, OpenImis.ModulesV3/InsureeModule/Repositories/FamilyRepository.cs, OpenImis.ModulesV3/InsureeModule/Repositories/InsureeRepository.cs, OpenImis.ModulesV3/ReportModule/Repositories/ReportRepository.cs, OpenImis.RestApi/config/appsettings.Development.json.dist, OpenImis.RestApi/config/appsettings.Production.json.dist
[https://openimis.atlassian.net/browse/OTC-659](https://openimis.atlassian.net/browse/OTC-659)
Changes:
- Added optional setting `ConnectionSettings:CommandTimeout` to appsettings
- Implemented variable command timeout for `DataHelper`, `ImisDB` and for commands created with `ImisDB.CreateCommand()`
- Changed DbCommand creation to `ImisDB.CreateCommand()` in V3 repositories
=> Enquire functionality on mobile application does not work

OpenImis.ModulesV3/Utils/PhotoUtils.cs
[https://openimis.atlassian.net/browse/OTC-674](https://openimis.atlassian.net/browse/OTC-674)
Changes:
- Added support for both `\` and `/` in paths in `PhotoUtils`
- Added safeguard against empty filename in `PhotoUtils`
=> OTC-674 When you enquire a CHF member you get the information of beneficiary, however no photo is displayed
