OpenImis.RestApi.IntegrationTests/LoginTests.cs, OpenImis.RestApi/Controllers/LoginControllerV1.cs, OpenImis.RestApi/Controllers/ValuesControllerV1.cs, OpenImis.RestApi/OpenImis.RestApi.csproj, OpenImis.RestApi/Properties/PublishProfiles/FolderProfile.pubxml, OpenImis.RestApi/Protocol/ARequestModel.cs, OpenImis.RestApi/Protocol/BadRequestModel.cs, OpenImis.RestApi/Protocol/IRequestModel.cs, OpenImis.RestApi/Protocol/LoginModels/LoginBadRequestModel.cs, OpenImis.RestApi/Protocol/LoginModels/LoginRequestModel.cs, OpenImis.RestApi/Protocol/LoginModels/LoginResponseModel.cs, OpenImis.RestApi/Startup.cs, README.md
=> added readme.md

OpenImis.DB.SqlServer/TblUsers.cs, OpenImis.Modules/UserModule/Repository/UserSQLServer.cs
ticket - https://openimis.atlassian.net/browse/OP-50
=> OP-50: Adjusted findByUsernameAndPassword code

OpenImis.Modules/CoverageModule/CoverageModule.cs, OpenImis.Modules/CoverageModule/Helpers/GetCoverageResponse.cs, OpenImis.Modules/CoverageModule/Helpers/ImisApiResponse.cs, OpenImis.Modules/CoverageModule/Helpers/Messages/Language.cs, OpenImis.Modules/CoverageModule/Helpers/Messages/PrimaryLanguage.cs, OpenImis.Modules/CoverageModule/Helpers/Messages/SecondaryLanguage.cs, OpenImis.Modules/CoverageModule/ICoverageModule.cs, OpenImis.Modules/CoverageModule/Logic/CoverageLogic.cs, OpenImis.Modules/CoverageModule/Logic/ICoverageLogic.cs, OpenImis.Modules/CoverageModule/Models/CoverageModel.cs, OpenImis.Modules/CoverageModule/Models/CoverageProduct.cs, OpenImis.Modules/CoverageModule/Models/DataMessage.cs, OpenImis.Modules/CoverageModule/Repositories/CoverageRepository.cs, OpenImis.Modules/CoverageModule/Repositories/ICoverageRepository.cs, OpenImis.Modules/IImisModules.cs, OpenImis.Modules/ImisModules.cs, OpenImis.RestApi/Controllers/CoverageController.cs
The `Coverage Module` has been added in the basic form. Validation and authorization will be added later in the WS integration with the REST API
TASK:
https://openimis.atlassian.net/browse/OS-23
=> OS-23: The Coverage Module has been added

OpenImis.Modules/IImisModules.cs, OpenImis.Modules/ImisModules.cs, OpenImis.Modules/LoginModule/ILoginModule.cs, OpenImis.Modules/LoginModule/Logic/ILoginLogic.cs, OpenImis.Modules/LoginModule/Logic/LoginLogic.cs, OpenImis.Modules/LoginModule/LoginModule.cs, OpenImis.Modules/LoginModule/Models/Language.cs, OpenImis.Modules/LoginModule/Models/LoginModel.cs, OpenImis.Modules/LoginModule/Models/Rights.cs, OpenImis.Modules/LoginModule/Models/UserData.cs, OpenImis.Modules/LoginModule/Models/UserLogin.cs, OpenImis.Modules/LoginModule/Models/ValidateCredentialsResponse.cs, OpenImis.Modules/LoginModule/Repositories/ILoginRepository.cs, OpenImis.Modules/LoginModule/Repositories/LoginRepository.cs, OpenImis.RestApi/Controllers/LoginController.cs
The Login Module has been added in the basic form. The module has an endpoint to log in and obtain a JWT token and Validate Credentials
TASK:
https://openimis.atlassian.net/browse/OS-24
=> OS-24: The Login Module has been added

OpenImis.Modules/ClaimModule/ClaimModule.cs, OpenImis.Modules/ClaimModule/IClaimModule.cs, OpenImis.Modules/ClaimModule/Logic/ClaimLogic.cs, OpenImis.Modules/ClaimModule/Logic/IClaimLogic.cs, OpenImis.Modules/ClaimModule/Models/ClaimAdminModel.cs, OpenImis.Modules/ClaimModule/Models/CodeName.cs, OpenImis.Modules/ClaimModule/Models/CodeNamePrice.cs, OpenImis.Modules/ClaimModule/Models/DiagnosisServiceItem.cs, OpenImis.Modules/ClaimModule/Models/DsiInputModel.cs, OpenImis.Modules/ClaimModule/Models/PaymentLists.cs, OpenImis.Modules/ClaimModule/Models/PaymentListsInputModel.cs, OpenImis.Modules/ClaimModule/Repositories/ClaimRepository.cs, OpenImis.Modules/ClaimModule/Repositories/IClaimRepository.cs, OpenImis.Modules/IImisModules.cs, OpenImis.Modules/ImisModules.cs, OpenImis.RestApi/Controllers/ClaimsController.cs
The Claim Module has been added
TASK:
https://openimis.atlassian.net/browse/OS-21
=> OS-21: The Claim Module has been added

OpenImis.Modules/PaymentModule/Helpers/Messages/SecondaryLanguage.cs
Replacing the SecondaryLanguage file with a French translation file
TASK:
https://openimis.atlassian.net/browse/OS-30
=> OS-30: Replacing the SecondaryLanguage file

OpenImis.ModulesV2/FeedbackModule/FeedbackModule.cs, OpenImis.ModulesV2/FeedbackModule/IFeedbackModule.cs, OpenImis.ModulesV2/FeedbackModule/Logic/FeedbackLogic.cs, OpenImis.ModulesV2/FeedbackModule/Logic/IFeedbackLogic.cs, OpenImis.ModulesV2/ImisModules.cs, OpenImis.ModulesV2/MasterDataModule/IMasterDataModule.cs, OpenImis.ModulesV2/MasterDataModule/Logic/IMasterDataLogic.cs, OpenImis.ModulesV2/MasterDataModule/Logic/MasterDataLogic.cs, OpenImis.ModulesV2/MasterDataModule/MasterDataModule.cs, OpenImis.ModulesV2/PremiumModule/IPremiumModule.cs, OpenImis.ModulesV2/PremiumModule/Logic/IPremiumLogic.cs, OpenImis.ModulesV2/PremiumModule/Logic/PremiumLogic.cs, OpenImis.ModulesV2/PremiumModule/PremiumModule.cs, OpenImis.ModulesV2/SystemModule/ISystemModule.cs, OpenImis.ModulesV2/SystemModule/Logic/ISystemLogic.cs, OpenImis.ModulesV2/SystemModule/Logic/SystemLogic.cs, OpenImis.ModulesV2/SystemModule/SystemModule.cs, OpenImis.RestApi/openImisModules.json
I added a new module to the project structure according to RFC 72.6
TASK:
https://openimis.atlassian.net/browse/OS-54
=> OS-54: Added support for new modules

OpenImis.ModulesV2/ClaimModule/ClaimModule.cs, OpenImis.ModulesV2/ClaimModule/Logic/ClaimLogic.cs, OpenImis.ModulesV2/ClaimModule/Logic/IClaimLogic.cs, OpenImis.ModulesV2/ClaimModule/Models/RegisterClaim/Claim.cs, OpenImis.ModulesV2/ClaimModule/Repositories/ClaimRepository.cs, OpenImis.ModulesV2/ClaimModule/Repositories/IClaimRepository.cs, OpenImis.ModulesV2/Helpers/Extensions.cs, OpenImis.ModulesV2/ImisModules.cs, OpenImis.RestApi/Controllers/V2/ClaimController.cs
I added a new module to the project
TASK:
https://openimis.atlassian.net/browse/OS-40
=> OS-40: Added Claim

OpenImis.ModulesV2/ClaimModule/Logic/ClaimLogic.cs, OpenImis.ModulesV2/ClaimModule/Logic/IClaimLogic.cs, OpenImis.ModulesV2/ClaimModule/Models/ClaimAdminModel.cs, OpenImis.ModulesV2/ClaimModule/Models/CodeName.cs, OpenImis.ModulesV2/ClaimModule/Models/CodeNamePrice.cs, OpenImis.ModulesV2/ClaimModule/Models/DiagnosisServiceItem.cs, OpenImis.ModulesV2/ClaimModule/Models/DsiInputModel.cs, OpenImis.ModulesV2/ClaimModule/Models/PaymentLists.cs, OpenImis.ModulesV2/ClaimModule/Models/PaymentListsInputModel.cs, OpenImis.ModulesV2/ClaimModule/Repositories/ClaimRepository.cs, OpenImis.ModulesV2/ClaimModule/Repositories/IClaimRepository.cs, OpenImis.RestApi/Controllers/V2/ClaimController.cs
The content of Claim was copied from API v1 to API version 2
TASK:
https://openimis.atlassian.net/browse/OS-60
=> OS-60: Copied Claim v1 to v2

OpenImis.DB.SqlServer/IMISContext.cs, OpenImis.DB.SqlServer/TblIMISDefaultsPhone.cs, OpenImis.ModulesV2/MasterDataModule/Repositories/MasterDataRepository.cs
Changing the name of the entity TblIMISDetaulsPhone to TblIMISDefaultsPhone
TASK:
https://openimis.atlassian.net/browse/OS-65
=> OS-65: Changed name table TblIMISDefaultsPhone

OpenImis.ModulesV2/ReportModule/Logic/IReportLogic.cs, OpenImis.ModulesV2/ReportModule/Logic/ReportLogic.cs, OpenImis.ModulesV2/ReportModule/Models/CumulativeIndicatorsResponseModel.cs, OpenImis.ModulesV2/ReportModule/Models/IndicatorRequestModel.cs, OpenImis.ModulesV2/ReportModule/Models/SnapshotRequestModel.cs, OpenImis.ModulesV2/ReportModule/Models/SnapshotResponseModel.cs, OpenImis.ModulesV2/ReportModule/Repositories/IReportRepository.cs, OpenImis.ModulesV2/ReportModule/Repositories/ReportRepository.cs, OpenImis.RestApi/Controllers/V2/ReportController.cs
TASK:
https://openimis.atlassian.net/browse/OS-68
=> OS-68: Added endpoints to Report

OpenImis.ModulesV2/IImisModules.cs, OpenImis.ModulesV2/PremiumModule/Logic/PremiumLogic.cs, OpenImis.ModulesV2/PremiumModule/Models/ReceiptRequestModel.cs, OpenImis.ModulesV2/PremiumModule/Repositories/IPremiumRepository.cs, OpenImis.ModulesV2/PremiumModule/Repositories/PremiumRepository.cs, OpenImis.RestApi/Controllers/V2/PremiumController.cs
TASK:
https://openimis.atlassian.net/browse/OS-69
=> OS-69: Added endpoint in Premium Module

OpenImis.ModulesV2/InsureeModule/Models/FamilyModel.cs, OpenImis.ModulesV2/InsureeModule/Models/InsureeModel.cs, OpenImis.RestApi/Controllers/V2/FamilyController.cs
TASK:
https://openimis.atlassian.net/browse/OS-70
=> OS-70: Added ID for Family and Insuree

OpenImis.ModulesV2/Helpers/GetCommissionResponse.cs, OpenImis.ModulesV2/Helpers/ImisApiResponse.cs, OpenImis.ModulesV2/Helpers/Messages/Language.cs, OpenImis.ModulesV2/Helpers/Messages/PrimaryLanguage.cs, OpenImis.ModulesV2/Helpers/Messages/SecondaryLanguage.cs, OpenImis.ModulesV2/InsureeModule/Models/EnrollFamilyModels/Family.cs, OpenImis.ModulesV2/InsureeModule/Models/EnrollFamilyModels/Insuree.cs, OpenImis.ModulesV2/InsureeModule/Models/EnrollFamilyModels/InsureeImage.cs, OpenImis.ModulesV2/InsureeModule/Models/EnrollFamilyModels/InsureePolicy.cs, OpenImis.ModulesV2/InsureeModule/Models/EnrollFamilyModels/Policy.cs, OpenImis.ModulesV2/InsureeModule/Models/EnrollFamilyModels/Premium.cs, OpenImis.ModulesV2/InsureeModule/Models/InsureeModel.cs, OpenImis.ModulesV2/InsureeModule/Repositories/FamilyRepository.cs, OpenImis.ModulesV2/MasterDataModule/Models/OfficerModel.cs, OpenImis.ModulesV2/MasterDataModule/Repositories/MasterDataRepository.cs, OpenImis.ModulesV2/PolicyModule/Logic/IPolicyRenewalLogic.cs, OpenImis.ModulesV2/PolicyModule/Logic/PolicyRenewalLogic.cs, OpenImis.ModulesV2/PolicyModule/Models/CommissionMode.cs, OpenImis.ModulesV2/PolicyModule/Models/DataMessage.cs, OpenImis.ModulesV2/PolicyModule/Models/GetCommissionInputs.cs, OpenImis.ModulesV2/PolicyModule/Repositories/IPolicyRenewalRepository.cs, OpenImis.ModulesV2/PolicyModule/Repositories/PolicyRenewalRepository.cs, OpenImis.RestApi/Controllers/V2/FamilyController.cs, OpenImis.RestApi/Controllers/V2/PolicyRenewalController.cs
TASK:
https://openimis.atlassian.net/browse/OS-41
=> OS-41: Added Commission and changes in Family

ImisRestApi/ImisRestApi/Escape/Payment/Data/GepgUtility.cs
Related tickets: 
https://openimis.atlassian.net/browse/OTC-118
https://openimis.atlassian.net/browse/OTC-119
=> OTC-119: Passing Accounting code as SpCode in gepgBillSub request

OpenImis.ModulesV2/InsureeModule/Models/DetailModel.cs, OpenImis.ModulesV2/InsureeModule/Repositories/InsureeRepository.cs
TICKET: [OP-264](https://openimis.atlassian.net/browse/OP-264)
=> OP-264: Added coverage data to enquire endpoint

ImisRestApi/Data/ImisBasePayment.cs, ImisRestApi/Escape/Payment/Controllers/PaymentController.cs, ImisRestApi/Escape/Payment/Data/GepgUtility.cs, ImisRestApi/Escape/Payment/Data/ImisPayment.cs, ImisRestApi/Extensions/GepgFoldersCreating.cs, ImisRestApi/appsettings.json
TICKET: https://openimis.atlassian.net/browse/OTC-270
Fixes:
1. changes in processing requests in some PaymentControllers
2. changes way of processing and naming json files for getControlNumber and getReqControlNumber Controllers.
=> OTC-270: ePayment fix request encoding UTF-16

ImisRestApi/Escape/Payment/Controllers/PaymentController.cs, ImisRestApi/Extensions/GepgFoldersCreating.cs, ImisRestApi/Formaters/GePGXmlSerializerInputFormatter.cs
TICKET: https://openimis.atlassian.net/browse/OTC-272
=> OTC-272: saving requests payload to special folder and changes in json files

OpenImis.ePayment/Escape/Payment/Controllers/PaymentController.cs, OpenImis.ePayment/Escape/Payment/Data/ImisPayment.cs, OpenImis.ePayment/Extensions/GepgFoldersCreating.cs, OpenImis.ePayment/Extensions/StringExtensions.cs, OpenImis.ePayment/Formaters/CallNumberStructure.cs, OpenImis.ePayment/Formaters/GePGXmlSerializerInputFormatter.cs, OpenImis.ePayment/Formaters/GepgCodeResponses.cs
TICKET: https://openimis.atlassian.net/browse/OTC-145 - new approach - changes from master_swiss related to ePayment integration
=> OTC-145: changes from masterswiss related to epayment integration

OpenImis.ePayment/Controllers/ClaimsController.cs, OpenImis.ePayment/Data/DataHelper.cs, OpenImis.ePayment/Data/ImisClaims.cs, OpenImis.ePayment/Models/ClaimOutPut.cs
Added changes from `feature/OTC-250`
[PR: https://github.com/openimis/rest_api_c-sharp/pull/64](https://github.com/openimis/rest_api_c-sharp/pull/64)
[Jira: https://openimis.atlassian.net/browse/OTC-250](https://openimis.atlassian.net/browse/OTC-250)
=> Added changes from feature/OTC-250

OpenImis.ePayment/Data/ImisBasePayment.cs, OpenImis.ePayment/Escape/Payment/Controllers/PaymentController.cs, OpenImis.ePayment/Escape/Payment/Data/ImisPayment.cs, OpenImis.ePayment/Escape/Payment/Models/PaymentStatus.cs
TICKET: https://openimis.atlassian.net/browse/OTC-114
Part related to make update of reconciliated payment from GePG. 
- update PaymentStatus = 5 for payment status < 5 and expectedAmount(IMIS)=amountPaid(GePG) and ReceivedAmount(IMIS) =amountPaid(GePG).
- update PaymentStatus = -5 for payment which are paid in GePG, but no info about paid in IMIS.
=> OTC-114: comparing reconciliation data and update payment status

OpenImis.ePayment/Data/ImisBasePayment.cs, OpenImis.ePayment/Escape/Payment/Controllers/PaymentController.cs, OpenImis.ePayment/Escape/Payment/Data/GepgUtility.cs, OpenImis.ePayment/Escape/Payment/Data/ImisPayment.cs, OpenImis.ePayment/Extensions/GepgFileLogger.cs, OpenImis.ePayment/Formaters/GePGXmlSerializerInputFormatter.cs, OpenImis.ePayment/Logic/PaymentLogic.cs, OpenImis.ePayment/Models/Payment/PaymentDetail.cs
TICKET: https://openimis.atlassian.net/browse/OTC-273
5. Split CN request bill per policies bill items BP001_11
contains changes from that PR: https://github.com/openimis/rest_api_c-sharp/pull/70
=> OTC-273:  Split CN request bill per policies bill items

OpenImis.ePayment/Escape/Payment/Controllers/PaymentController.cs, OpenImis.ePayment/Escape/Payment/Data/ImisPayment.cs, OpenImis.ePayment/Extensions/GepgFileLogger.cs, OpenImis.ePayment/Formaters/GePGXmlSerializerInputFormatter.cs
TICKET: https://openimis.atlassian.net/browse/OTC-273
4. stop 0 value on imis api
=> OTC-273: do not send request to GePG with amount <=0

OpenImis.ePayment/Escape/Payment/Data/ImisPayment.cs
part of ticket: https://openimis.atlassian.net/browse/OTC-273
=> OTC-273: suppport timeout issue

OpenImis.RestApi/Escape/Sms/Strings/CancellationSms.txt, OpenImis.RestApi/Escape/Sms/StringsSecondaryLanguage/CancellationSms.txt, OpenImis.ePayment/Data/ImisBasePayment.cs, OpenImis.ePayment/Escape/Payment/Data/ImisPayment.cs, OpenImis.ePayment/Logic/PaymentLogic.cs
part of TICKET: https://openimis.atlassian.net/browse/OTC-273
sending Cancellation SMS after cancelling payment. Including change with concatenating errors in RejectedReason column of tblPayment.
=> OTC-273: send SMS after cancelling payment

OpenImis.ePayment/Data/ImisBasePayment.cs
part of TICKET: https://openimis.atlassian.net/browse/OTC-273
=> OTC-273: concatenate error in RejectedReason

OpenImis.DB.SqlServer/TblReporting.cs, OpenImis.ModulesV3/PolicyModule/Repositories/PolicyRenewalRepository.cs
Changes:
- `tblReporting` entity model now includes `ReportMode` property
- Fixed errors in `GetCommissions` query
[https://openimis.atlassian.net/browse/OTC-324](https://openimis.atlassian.net/browse/OTC-324)
=> OTC-324: Fix check commission functionality

OpenImis.ePayment/Escape/Payment/Data/GepgUtility.cs
https://openimis.atlassian.net/browse/OTC-363
=> OTC-363: Missing ValidityTo in where criteria is added

OpenImis.DB.SqlServer/TblPolicy.cs, OpenImis.DB.SqlServer/TblPremium.cs, OpenImis.ModulesV3/InsureeModule/IInsureeModule.cs, OpenImis.ModulesV3/InsureeModule/Logic/FamilyLogic.cs, OpenImis.ModulesV3/InsureeModule/Logic/IFamilyLogic.cs, OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/EnrollFamilyModel.cs, OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/Enrolment.cs, OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/Insuree.cs, OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/NewFamilyResponse.cs, OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/Policy.cs, OpenImis.ModulesV3/InsureeModule/Repositories/FamilyRepository.cs, OpenImis.ModulesV3/InsureeModule/Repositories/IFamilyRepository.cs, OpenImis.RestApi/Controllers/V3/FamilyController.cs
https://openimis.atlassian.net/browse/OTC-329
=> OTC-329 : REST API POST Family should return HTTP 200 with db UUIDs in payload

OpenImis.ePayment/Controllers/PaymentBaseController.cs, OpenImis.ePayment/Escape/Payment/Data/ImisPayment.cs, OpenImis.ePayment/Logic/PaymentLogic.cs
https://openimis.atlassian.net/browse/OTC-384
=> OTC-384: If the count of CNs are less than threshold, fire another request to GePG to create CNs

OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/Insuree.cs, OpenImis.RestApi/Properties/PublishProfiles/FolderProfile.pubxml
https://openimis.atlassian.net/browse/OTC-385
=> OTC-385: Vulnerability field is present twice in Insuree model

OpenImis.RestApi/Properties/PublishProfiles/FolderProfile.pubxml, OpenImis.ePayment/Data/ImisBasePayment.cs
https://openimis.atlassian.net/browse/OTC-387
=> OTC-387: Compilation error in MV version

OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/Policy.cs, OpenImis.ModulesV3/InsureeModule/Repositories/FamilyRepository.cs, OpenImis.RestApi/Controllers/V3/FamilyController.cs
https://openimis.atlassian.net/browse/OTC-371
=> OTC-371: Accommodated Control Number in Family sync

OpenImis.ePayment/Escape/Payment/Data/ImisPayment.cs, OpenImis.ePayment/Escape/Payment/Models/BulkControlNumbersForEO.cs
https://openimis.atlassian.net/browse/OTC-391
This commit actually resolves the issue OTC-391
=> OTC 391: Assign Phone number of the officer during fetching the control numbers

OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/EnrollFamilyModel.cs, OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/Family.cs, OpenImis.ModulesV3/InsureeModule/Models/FamilyModel.cs, OpenImis.ModulesV3/InsureeModule/Models/FamilySMS.cs, OpenImis.ModulesV3/InsureeModule/Repositories/FamilyRepository.cs
https://openimis.atlassian.net/browse/OTC-394
=> OTC-394: Missing data model and code for Policy Notification in API V3

OpenImis.ModulesV3/ClaimModule/Models/ClaimAdminModel.cs, OpenImis.ModulesV3/ClaimModule/Repositories/ClaimRepository.cs, OpenImis.RestApi/Properties/PublishProfiles/FolderProfile.pubxml, OpenImis.RestApi/Properties/PublishProfiles/FolderProfile1.pubxml
https://openimis.atlassian.net/browse/OTC-396
=> OTC-396: Add HFCode in the endpoint GetClaimAdmins

OpenImis.ModulesV3/FeedbackModule/Models/Feedback.cs, OpenImis.ModulesV3/FeedbackModule/Models/FeedbackRequest.cs, OpenImis.ModulesV3/InsureeModule/Models/InsureeModel.cs, OpenImis.ModulesV3/PolicyModule/Models/GetPolicyRenewalModel.cs, OpenImis.ModulesV3/PolicyModule/Models/PolicyRenewalModel.cs, OpenImis.ModulesV3/PolicyModule/Repositories/PolicyRenewalRepository.cs, OpenImis.ModulesV3/ReportModule/Models/IndicatorRequestModel.cs, OpenImis.ModulesV3/ReportModule/Models/SnapshotRequestModel.cs, OpenImis.ModulesV3/ReportModule/Repositories/ReportRepository.cs
https://openimis.atlassian.net/browse/OTC-410
=> OTC-410: Change all the dates from string to datetime in rest api

OpenImis.ModulesV3/FeedbackModule/Models/Feedback.cs, OpenImis.ModulesV3/FeedbackModule/Models/FeedbackRequest.cs, OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/Insuree.cs, OpenImis.ModulesV3/InsureeModule/Models/InsureeModel.cs, OpenImis.ModulesV3/OpenImis.ModulesV3.csproj, OpenImis.ModulesV3/PolicyModule/Models/GetPolicyRenewalModel.cs, OpenImis.ModulesV3/PolicyModule/Models/PolicyRenewalModel.cs, OpenImis.ModulesV3/PolicyModule/Repositories/PolicyRenewalRepository.cs, OpenImis.ModulesV3/ReportModule/Models/IndicatorRequestModel.cs, OpenImis.ModulesV3/ReportModule/Models/SnapshotRequestModel.cs, OpenImis.RestApi/Properties/PublishProfiles/FolderProfile1.pubxml
https://openimis.atlassian.net/browse/OTC-410
=> OTC:410-Change all the dates from string to datetime in rest api

OpenImis.ModulesV3/InsureeModule/Logic/InsureeLogic.cs, OpenImis.ModulesV3/InsureeModule/Models/GetEnquireModel.cs, OpenImis.ModulesV3/InsureeModule/Models/GetInsureeModel.cs
https://openimis.atlassian.net/browse/OTC-411
=> OTC-411: Get insuree image as base64 instead of link in Enquire 

OpenImis.RestApi/Properties/PublishProfiles/FolderProfile2.pubxml, OpenImis.ePayment/Data/ImisBasePayment.cs, OpenImis.ePayment/Escape/Payment/Controllers/PaymentController.cs, OpenImis.ePayment/Escape/Payment/Models/PaymentStatus.cs
https://openimis.atlassian.net/browse/OTC-488
=> OTC-488: Don't change Payment status to 5 when doing reconciliation 

OpenImis.ModulesV3/FeedbackModule/Repositories/FeedbackRepository.cs
Changes:
- Updated `FeedbackRepository` to use ISO date format
[https://openimis.atlassian.net/browse/OP-459](https://openimis.atlassian.net/browse/OP-459)
=> OP-459: Feedback does not upload correctly

OpenImis.ModulesV3/ClaimModule/Repositories/ClaimRepository.cs
https://openimis.atlassian.net/browse/OTC-390
Changes:
- Fixed stored sql procedure
=> OTC-390: Updated stored procedure uspRestApiUpdateClaimFromPhone

OpenImis.ModulesV3/PolicyModule/Repositories/PolicyRenewalRepository.cs
https://openimis.atlassian.net/browse/OTC-173
Changes:
* Fixed bug - app user can send empty value in month field, while using check comission feature in app, causing backend server to crash. 
* Now when no month is choosen app make a query for every month in the given year.
=> OS-173: Fixed bug with unhandled exception.

OpenImis.ModulesV2/Helpers/Messages/PrimaryLanguage.cs, OpenImis.ModulesV2/InsureeModule/Repositories/FamilyRepository.cs, OpenImis.ModulesV3/Helpers/Messages/PrimaryLanguage.cs, OpenImis.ModulesV3/InsureeModule/Logic/FamilyLogic.cs, OpenImis.ModulesV3/InsureeModule/Logic/IFamilyLogic.cs, OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/EnrollFamilyModel.cs, OpenImis.ModulesV3/InsureeModule/Repositories/FamilyRepository.cs, OpenImis.ModulesV3/InsureeModule/Repositories/IFamilyRepository.cs, OpenImis.RestApi/Controllers/V3/FamilyController.cs, OpenImis.ePayment/Escape/Payment/Data/SingleControlNumberHandler.cs
https://openimis.atlassian.net/browse/OP-477
Changes:
- Enrollment/Enroll changed to enrolment/enrol in variable names/strings etc.
- Some instances were left unchanged - SQL queries, XML instances and so on, as to not brake compatibility.
=> OP-477: Enrollment changed to enrolment when feasible.

OpenImis.ePayment/Controllers/PaymentBaseController.cs, OpenImis.ePayment/Escape/Payment/Controllers/PaymentController.cs
Changes:
- Fixed broken virtual method chain leading to swagger crash
- Added explicit error message for Bulk CN Request, replacing a vague message
=> Rest Api swagger fix

OpenImis.ePayment/Controllers/PaymentBaseController.cs, OpenImis.ePayment/Data/DataHelper.cs, OpenImis.ePayment/Escape/Payment/Data/ImisPayment.cs, OpenImis.ePayment/Logic/PaymentLogic.cs
https://openimis.atlassian.net/browse/OTC-576
=> OTC-576: Get control numbers for EO sometimes throws the TimeOut error

OpenImis.RestApi/OpenImis.RestApi.csproj, OpenImis.ePayment/Extensions/GepgFileLogger.cs
Added try/catch in GepgFileLogger
https://openimis.atlassian.net/browse/OTC-585
=> OTC-585: Rest API frequently needs recycling of the pool

OpenImis.ePayment/Escape/Payment/Data/GepgUtility.cs
Changes:
- Changed wrong serialized object in CreateGePGCancelPaymentRequest
- Changed wrong target type in CreateBulkBills
=> OTC-586: Fixed Cn request XML serialization

OpenImis.ModulesV3/InsureeModule/Repositories/FamilyRepository.cs
Handled null control number
https://openimis.atlassian.net/browse/OTC-597
=> OTC-597: Null Exception (Control Number) in Create Family

OpenImis.ModulesV3/InsureeModule/Repositories/FamilyRepository.cs, OpenImis.RestApi/Controllers/V3/FamilyController.cs
This PR resolves 2 issues:
https://openimis.atlassian.net/browse/OTC-603
https://openimis.atlassian.net/browse/OTC-604
=> OTC-603: Create directories based on dates of enrolment to save the enrolment files

OpenImis.ModulesV3/InsureeModule/Repositories/FamilyRepository.cs, OpenImis.RestApi/Controllers/V3/ClaimController.cs, OpenImis.ePayment/Escape/Payment/Controllers/PaymentController.cs
[https://openimis.atlassian.net/browse/OTC-596](https://openimis.atlassian.net/browse/OTC-596)
Changes:
- Added logging for null family policy error spotted on prod in `FamilyRepository`
- Fixed validating model after usage in `PaymentController`
=> OTC-596: Added logging for FamilyRepository

README.md
Added more precise database connection configuration instruction.
=> OP-238: Improve setup steps in README.md

OpenImis.ModulesV3/InsureeModule/Models/GetEnquireModel.cs, OpenImis.ModulesV3/InsureeModule/Models/GetInsureeModel.cs, OpenImis.ModulesV3/InsureeModule/Repositories/InsureeRepository.cs
https://openimis.atlassian.net/browse/OTC-608
=> OTC-608: Add 2 extra fields Lastname and Othernames separately in the Enquire endpoint

OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/EnrollFamilyModel.cs, OpenImis.ModulesV3/InsureeModule/Models/EnrollFamilyModels/Enrolment.cs, OpenImis.ModulesV3/InsureeModule/Repositories/FamilyRepository.cs, OpenImis.ModulesV3/PolicyModule/Repositories/PolicyRenewalRepository.cs, OpenImis.ePayment/Data/ImisBasePayment.cs, OpenImis.ePayment/Escape/Payment/Data/ImisPayment.cs, OpenImis.ePayment/Logic/PaymentLogic.cs
https://openimis.atlassian.net/browse/OTC-616
=> OTC-616: Add new columns related to the source of the entries in all the enrolment related tables 

OpenImis.ModulesV3/ClaimModule/Logic/ClaimLogic.cs, OpenImis.ModulesV3/ClaimModule/Models/SubmitClaimResponse.cs, OpenImis.ModulesV3/ClaimModule/Repositories/ClaimRepository.cs
https://openimis.atlassian.net/browse/OTC-614
=> OTC-614: Submitting claim in REST API, return error message when the items/services are rejected

OpenImis.ModulesV3/InsureeModule/Logic/InsureeLogic.cs, OpenImis.ModulesV3/InsureeModule/Models/InsureeModel.cs, OpenImis.ModulesV3/InsureeModule/Repositories/FamilyRepository.cs, OpenImis.ModulesV3/Utils/PhotoUtils.cs
[https://openimis.atlassian.net/browse/OTC-640](https://openimis.atlassian.net/browse/OTC-640)
Changes:
- Fixed photoPath assembling in `Modify Family` and `Enquire`
- Updated family repository to use `tblLocations` instead of the old tables
=> OTC-640 The app freezes when using "Modify Family"

OpenImis.ModulesV3/ClaimModule/ClaimModule.cs, OpenImis.ModulesV3/ClaimModule/Logic/ClaimLogic.cs, OpenImis.ModulesV3/ClaimModule/Repositories/ClaimRepository.cs, OpenImis.ModulesV3/ImisModules.cs
[https://openimis.atlassian.net/browse/OP-943](https://openimis.atlassian.net/browse/OP-943)
Changes:
- Added `logger factory` to claim `module`, `logic` and `repository`
- Added `logger` to claim repository
- Added missing logging calls to `create claim` feature
- Added result code to `Unhandled exception` message
=> OP-943 Added missing logging in posting claims
